### ISSUE TITLE
Обход анализа PT AI разработчиком путем формирования специального .aiignore файла

### ISSUE THREAD

**Issue by sergiomarotco** [POSIdev-community/ptai-analysis-rules#11]
Если разработчик умудрится прописать в файл .aiignore текст `*.*`, то все файлы будут исключены из сканирования и проверка PT AI всегда будет давать успех так как все файлы будут пропущены.
Заметил, что все же файлы вида **.чтототам** не исключаются из проверки:
![image](https://github.com/POSIdev-community/ptai-analysis-rules/assets/29877074/8bade150-6ca9-4523-ad88-f4e99eeb39a5)
![image](https://github.com/POSIdev-community/ptai-analysis-rules/assets/29877074/3391db44-f15d-4ee6-97ee-45a2204b3362)

Временная мера:
Реализовать проверку в коде валидационных сборок вида:

```powershell
# Проверка создания исключений разработчиками в PowerShell
if(Test-Path "${Path_to_analyze}/.aiignore" -PathType leaf)
{
    # Валим валидационную сборку, для Azure DevOps это будет так:
    Write-Host "##vso[task.logissue type=error;]Репозиторий содержит файл .aiignore, удалите файл .aiignore"
    Write-Host "##vso[task.complete result=Failed;]"
    Write-Host "##[warning]Репозиторий содержит файл .aiignore, удалите файл .aiignore"
    Write-Host $Error
}
```
Или
```bash
# Проверка в bash создания файла .aiignore в репозитории, это может привести к несанкционированному исключению файлов из сканирования
if test -f "$Path_to_analyze/.aiignore"; then
    echo "##[warning]Репозиторий содержит файл .aiignore, удалите файл .aiignore"
    echo "##vso[task.logissue type=error;]Репозиторий содержит файл .aiignore, удалите файла .aiignore";
    exit 1
fi
```

**Comment by vldF** [comment]
Кажется, issue застоялся.

Может, было бы лучше перенести этот совет в виде скрипта в https://github.com/POSIdev-community/ptai-scripts? Кажется, что ничего конструктивнее в рамках сообщества мы сделать не можем.

Если Вам кажется, что этот совет всё ещё актуален, заведите PR/issue в другой репозиторий.

**Comment by sergiomarotco** [comment]
То чувство, когд зарепортил уязвимость из Cider CI/CD risks TOP 1:

_Establish pipeline flow control mechanisms to ensure that no single entity (human / programmatic) is able to ship sensitive code and artifacts through the pipeline without external verification or validation_

Но всем все равно:(

**Comment by vldF** [comment]
К сожалению, поддержка PT AI происходит не через issues в этом репозитории
