### ISSUE TITLE
Будет ли разбитие папок по языкам?

### ISSUE THREAD

**Issue by sergiomarotco** [POSIdev-community/ptai-analysis-rules#2]
Привет! Было бы удобно, например, нужно мне скачать все правила по языку C#, зашел в папку и скачал их. Сейчас же чтобы понять по какому языку правило, необходимо его сначала открыть.

**Comment by vldF** [comment]
Спасибо за Issue!

Для этого пришлось бы поддерживать несколько копий одного и того же правила в разных местах. Это не всегда было бы просто и приводило бы к путанице

Есть несколько вариантов решения проблемы, но пока надо понять, в какую сторону будет двигаться сообщество. Сейчас правил немного и, если в какой-то момент навигация станет сложной, будем что-то делать
