### ISSUE TITLE
Инструкция по переносу DSL 

### ISSUE THREAD

**Issue by sergiomarotco** [POSIdev-community/ptai-analysis-rules#6]
Привет! Перенес [Information Exposure Through an Error Message.json
](https://github.com/POSIdev-community/ptai-analysis-rules/blob/main/examples/rules/Information%20Exposure%20Through%20an%20Error%20Message.json) в PT AI так:
![image](https://github.com/POSIdev-community/ptai-analysis-rules/assets/29877074/9e9db459-9254-4abb-84dc-68460be87678)
Словил ошибки:

- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input '{' expecting {Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [1,1..2).
- Строка1
- Колонка1
- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input ':' expecting {<EOF>, Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [2,10..11).
- Строка2
- Колонка10
- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input ',' expecting {<EOF>, Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [2,59..60).
- Строка2
- Колонка59
- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input ':' expecting {<EOF>, Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [3,16..17).
- Строка3
- Колонка16
- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input ',' expecting {<EOF>, Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [3,26..27).
- Строка3
- Колонка26
- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input ':' expecting {<EOF>, Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [4,17..18).
- Строка4
- Колонка17
- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input ',' expecting {<EOF>, Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [4,24..25).
- Строка4
- Колонка24
- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input ':' expecting {<EOF>, Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [5,12..13).
- Строка5
- Колонка12
- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input ',' expecting {<EOF>, Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [5,35..36).
- Строка5
- Колонка35
- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input ':' expecting {<EOF>, Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [6,23..24).
- Строка6
- Колонка23
- Pattern edc9498f-686f-4e2c-8eb8-c284ca1f5caa ParsingException: extraneous input '}' expecting {<EOF>, Comment, Null, Bool, 'new', 'try', 'function', 'class', 'field', 'return', 'throw', 'base', '#', Ellipsis, '(', '<[', '<~>', '<{', Id, String, Oct, Int, Hex} at [7,1..2).
- Строка7
- Колонка1

Так как правильно переносить правила? Также прошу вас разместить инструкцию в основном readme.md о том как переносить.

**Comment by vldF** [comment]
Я же верно понимаю, что issue больше не про вашу конкретную проблему (потому что, судя по чату, Вы уже давно пользуетесь правилами, да и два PRа говорят про то же), а про то, чтобы мы добавили инструкцию про то, как поля из JSON описания правила соотносятся с полями в UI?

**Comment by sergiomarotco** [comment]
@vldF Владислав, верно.

**Comment by vldF** [comment]
Приветствую! В рамках #14 мы провели масштабную миграцию существующих правил с учётом новой фичи на импорт и экспорт PM правил в PT AI. В том числе улучшили документацию. В знак уважения к Вашему вкладу, мы оставили Ваш GH аккаунт в поле контактов с автором тех правилах, которые были отправлены Вами. При желании можете поменять это поле PRом

Кажется, теперь этот issue неактуален, так как связь между полями в json и настройками в UI стала более понятной. Если это не так, дайте знать
